### ISSUE TITLE
Start up freezes on "OPENCL#1: 99%"

### ISSUE THREAD

**Issue by domfgbrown** [Genoil/cpp-ethereum#141]
`OPENCL#1: 90%
OPENCL#0: 92%
OPENCL#2: 94%
OPENCL#1: 91%
OPENCL#0: 93%
OPENCL#2: 95%
OPENCL#1: 92%
OPENCL#0: 94%
OPENCL#2: 96%
OPENCL#1: 92%
OPENCL#0: 95%
OPENCL#2: 97%
OPENCL#1: 93%
OPENCL#0: 96%
OPENCL#2: 98%
OPENCL#1: 94%
OPENCL#0: 97%
OPENCL#2: 98%
OPENCL#1: 95%
OPENCL#0: 98%
OPENCL#2: 99%
OPENCL#1: 96%
OPENCL#0: 98%
OPENCL#0: 99%
OPENCL#1: 97%
OPENCL#1: 98%
OPENCL#1: 98%
OPENCL#1: 99%
`

I have 3 rx480 on ubuntu 16.04

**Comment by xavierzwirtz** [comment]
Also having the same issue, with a single rx480. Were you able to fix this @domfgbrown?

**Comment by porter707** [comment]
Also have the same issue single r290x any fix ?

**Comment by RB3rg** [comment]
Same same with RX480.

**Comment by andrewostroumov** [comment]
Same on RX480

**Comment by jrnewell** [comment]
If you are using ubuntu, try using amdgpu pro 16.40 drivers.  Anything newer and mine freezes too at 99% (rx 480).

**Comment by BruceBuckland** [comment]
There is another approach - install 16.6 ( I haven't tried 17.1) and then downgrade the icd part to 16.40 ( the process is explained ( and whay it is needed) here)...
https://github.com/genesismining/sgminer-gm/wiki/Compile-sgminer-5.5.5-in-Ubuntu-16.04.1-LTS#212-amd-linux-graphics-driver-amdgpu-pro

As is explain ( thanks e.g. mining) ...
amdgpu-pro version 16.50 contains a newer OpenCL compiler which causes problems with current sgminer versions. Possible solutions include using version 16.40, or installing the 16.50 driver, then overwriting the OpenCL ICD files with the versions from 16.40. This hybrid approach, whilst perhaps less than ideal, gains you the stability of the newer driver whilst maintaining the ability to compile working OpenCL kernels.

**Comment by andrewostroumov** [comment]
I have install 16.40 drivers. And 99% freeze was here until commented export GPU_FORCE_64BIT_PTR=0

```
#!/bin/sh

#export GPU_FORCE_64BIT_PTR=0
export GPU_MAX_HEAP_SIZE=100
export GPU_USE_SYNC_OBJECTS=1
export GPU_MAX_ALLOC_PERCENT=100
export GPU_SINGLE_ALLOC_PERCENT=100

/home/frodo/cpp-ethereum/build/ethminer/ethminer --farm-recheck 200 -G -S etc-eu1.nanopool.org:19999 -FS etc-eu2.nanopool.org:19999 -O wallet/rig/email
```

**Comment by andrewostroumov** [comment]
But this miner get me 26-27 Mh/s. Claymore - 29 Mh/s.

**Comment by BruceBuckland** [comment]
Same here on 4gb rx470 and rx480

**Comment by BruceBuckland** [comment]
Is that based on calculated hash rate or reported? I have seen the same difference in reported hashrate but less of a difference in found shares... lots of people use claymore so even though you can't see the code it is unlikely that they are just adding 2 to hashrate ( I hope).

**Comment by jrnewell** [comment]
Are you guys overclocking or modifying your BIOS?  I seem to only get ~22 stock with both genoil and claymore.

**Comment by Bluebugs** [comment]
Using amdgpu-pro with AMD driver 16.60 on a RX 480 with kernel 4.9.25, ethminer get stuck at 99% while claymore does work. No warning or crash in any log can be seen. Let me know if there is anything I can test to help narrow the issue.

**Comment by renaudcerrato** [comment]
Same thing on RX580 using 16.60: stuck at 99%. Since I'm on kernel 4.8, I'll downgrade to 4.4 to be able to use drivers 16.40.

**Comment by BruceBuckland** [comment]
@jrnewell yes, vbios modified.  On the RX480 and RX470 for Ethereum you will get better results if you LOWER the sclk and raise the mclk.  Also you should change the memory timing "straps".  There is a tool in Windows to do this, forget it's name, just search.  The memory straps can be done a simple way... just use the 1500MHZ strap for all the speeds higher than 1500.  IF this causes problems try using the 1625 strap for all the higher timings.  Depending upon the memory type in your card (Elpida, Samsung, Hynix etc) you may be able to push things more or less.  There is a lot of stuff online about modding bios, much of it is useless, but some of it will help.  Don't push things too far all at once (because you want to be able to at least boot to remove the change if it doesnt work.).  It helps if you have more than one card available to you.  In any case, for the 470's I do sclk 1150 mclk 2040.... I have one card that wont let me mclk over 1920.  I also have some samsung 470s that wont let me go mclk over 2000 but they will allow sclk of 1180.  At the lower clock rate they use a lot less power too, and my hash rate for a set of 7 rx470s is about 188MHps over a 6 hour time period.  Here are the clocking I use on that group (8 are Elpida and one is samsung.  one of the elpida is touchy so I clocked it slow)

` 51℃   card: 0 fan: 21% load: 100% mem clock:1920 MHz gpu clock:1150 MHz
 51℃   card: 1 fan: 28% load: 100% mem clock:2040 MHz gpu clock:1150 MHz
 52℃   card: 2 fan: 32% load: 100% mem clock:2040 MHz gpu clock:1150 MHz
 51℃   card: 3 fan: 31% load: 100% mem clock:2040 MHz gpu clock:1150 MHz
 51℃   card: 4 fan: 47% load: 100% mem clock:2040 MHz gpu clock:1150 MHz
 52℃   card: 5 fan: 32% load: 100% mem clock:2000 MHz gpu clock:1180 MHz
 52℃   card: 6 fan: 40% load: 100% mem clock:2040 MHz gpu clock:1150 MHz`

The RX480's can hash even faster, but use a lot more power.  The difference in power usage (i found) is not worth the money or the increased hashrates.  But I have a few and I have them clocked low.  I use the 1500 or 1625 memory straps and they do ok... and that keeps them cool and using less power and they hash a little faster than the 470s.  But in Ether per Watt... the 480's always lose.

These are a couple of 480s

` 59℃   card: 0 fan: 47% load: 100% mem clock:2000 MHz gpu clock:1150 MHz
 59℃   card: 1 fan: 56% load: 100% mem clock:2020 MHz gpu clock:1150 MHz`

**Comment by jrnewell** [comment]
Hey, @BruceBuckland.  That was very helpful, thank you!

Is this the vbois editor you used, https://github.com/caa82437/PolarisBiosEditor?  I ended up following this guide http://cryptoyeti.com/rx470-bios-mod/ and your post to mod my rx470s using a Windows 10 To Go external hard drive.  I will try my rx480s next.

The part about copying the 1500 memory timing strap is pretty straight forward.  I am little bit confused about changing the sclk and mclk.  What I ended up doing is changing the second value in the "Memory" section of the PolarisBiosEditor for the mclk.  For the sclk, I changed all of the Mhz values except for the first one to 1180 in the "GPU" section.  Is this the correct way to do this?  Do you need to mod the voltage at all?

My rx470s seem to be Samsung memory :( - so I ended up doing 1500 strap, 1920 mclck, and 1180 sclck.  Anything higher in the mclck setting, and I start to get GPU errors spitting out to my console.  With these settings - I seem to get ~24/25 MHash.  However, the issue I am having now is that the calculated speeds from dwarfpool is only about half of my reported speed.  I assume that means I need to reduce the mclck a bit?  Have you seen that before or have any advice?

Thanks again for all of your help!  One last thing, do you flash with your risers or straight from the board?  It is a pain in the butt to swap our the cards two at a time, but I don't really trust the risers not to crap out at the wrong time.

**Comment by BruceBuckland** [comment]
@jrnewell yes... polaris bios editor.  

The memory timings alone make a huge difference in hashrate.  I imagine there are people that have figured out the memory straps and can do a much better job of it, but ethereum mining is memory timing sensitive.

I do my tuning using the latest Claymore (--benchmark mode) on a windows box... bigger hashrates are better (but I never believe the actual hashrates).  The best real measure of hashrates is long term shares found on a mining pool (like nanopool).  But these hashrates (I havent tried dwarfpool) are subject to luck and the reporting system of the pool, so they may vary all over the place - and are really useful only over 6 - 12 - 24 hours or more. So they make a very poor tuning tool where you need immediate feedback. 
 
Windows tools also let you play around with the clocks to see the effect on stability and hashrate (though in Claymore you should stop and start the GPU when you change the clocks, in order to see the effect the change had). 

My mining is done on ubuntu (linux) and using AMDGPU-PRO drivers and so setting the clocks is problematic.  You can set the clocks using sysfs files but the problem is that the memory clock changes are reported but do not seem to have an effect on hashrate.  I have found that I can use that sysfs method to select the performance band to lower the sclk rate and it actually works (at least on kernel 4.9 it does) but I have stopped all that and what I do is just use polaris bios editor to lower the clock rate of the top few performance bands so that the very top clock is the one I want to use.  I don't change the voltage value... I just lower the clocks.

I will say that with the memory clocks I have found (sometimes) that changing the voltage is helpful.  It is particularly useful to try this out in windows because you can change it all live.  The memory voltage value LOWER (935 mv or 961 mv) on some of my rx480s made it so I could clock the memory higher.

But stability really matters because these GPU's when they hang keep sucking power sometimes.  Some of my GPU's hang every day or so if the temperature gets warmer in the room.   So I have a little web-relay box I bought on Amazon for $50 and I have scripts in each rig that watch the next using the nanopool api.  If the hash rate drops, or an email comes in that says my worker went offline, the script will shutdown the machine and then hard power cycle it.  This gives me good continuous hashing and gives me time to clean up the unstable GPU's.  (The biggest problem is figuring out which ones are troublesome.)

As far as flashing is concerned:

BTW be careful when you do your RX4.. cards, use atiflash to get a safe copy of your bios... I use another GPU tool to back up bios once and it didn't copy the whole bios.

I know that the guides all say pull the cards, and flash on a machine with one card.  I ignore that and do what i want (I am in this for the learning ... I don't care if I fry a card... but I have had no trouble yet with this method).  I use atiflash commandline flashing (not the atiwinflash version).   So yes, I flash my cards in place without disconnecting anything.  I flash on a single machine with an asrock btc motherboard.  (That said, I have the powered risers that are pretty good normal quality usb connected, not the ones that are unpowered with ribbon cables etc. some of which look a bit shaky.)

I always flash with no other miner or overclock tool running on windows... like the guides say... but I don't know if this matters.   

I will say that windows takes FOREVER to configure changes in GPUs, so I try to keep the GPU count and type the same so windows can figure out what the cards are (if I add more GPU's than windows last booted with... I have to wait 10 minutes while it figures it out).

for your specific card (brand, revision and memory type) there may be bios's you can find online.  I am surprised at how many bioses online are clocked high (so they guzzle power) with no real advantage for ethereum.  But maybe mining other stuff needs the clock.

What specific type and brand of cards are you running?

As far as the low reported hashrates from dwarfpool are concerned... I have seen cases where there are errors and ethminer reports one hashrate, and nanopool reports much less..... but in those cases  I looked at the ethminer logs and found that the number of submitted and accepted shares was much lower for a couple of cards... so I changed the vbios on those.   I have a linux script called worst-card that takes the log and reports submitted shares and stales so I can see if there are cards that are having problems.  I don't know how dwarfpool works but usually it is about submitted and accepted shares so you have some logging of that even when you set logging level to 1 (-v 1).

Are you running linux? amdgpu-pro? what versions?

**Comment by jrnewell** [comment]
Hey @BruceBuckland , thanks for your info that was quite helpful!

I have mostly have two model of cards: MSI 470 Armor 4G and MSI 480 Gaming X 4G and running ubuntu 16.04.2 servers headless, amdgpu pro 14.40 driver

I think i figured out my issue and got my two rigs in a good state.  I followed your advice and used atiflash command with the risers and everything was OK - also made sure to back up the bios using atiflash too.  The only thing I couldn't do was test in Windows - it looks like there is some BIOS signature check or something that was added to the latest windows AMD drivers.  I ended up using claymore on ubuntu and it gave me more information about when bad shares were being generated due to overclocking.  I just dialed them back a bit until I didn't see those messages anymore.  The calc rate now roughly matches the sent rate with the usual variance.  I also noticed that claymore has a better hashrate than genoil when you change the clock settings (didn't notice any difference before I modded the bios).  Right now, my 470 Armors are hashing around 26 and and my 480 gaming are hashing 29.  They seem to be pretty stable so I am happy with these results.

The next thing I am going to look into is installing the 4.10 kernel and upgrading the amdgpu-pro drivers to 16.6 and maybe trying out sgminer.  It seems like it is getting harder to find 400 cards anymore and you need the latest amd (15.1?) drivers to run the 500 cards.

That idea about using a relay box and hard-restarting the rigs seems like a good idea.  I was looking into getting one of those "smart plugs" so I could do a hard reset of hung rigs remotely and monitor my electric usage.
