### ISSUE TITLE
Could you please advices to run efficiently

### ISSUE THREAD

**Issue by sahara108** [Genoil/cpp-ethereum#169]
Hi all, I am new here and don't know how to start. Could you please advices which platform should I start (linux or windows) and the recommended hardware. Many thanks

**Comment by jjisnow** [comment]
0. Hardware - a late edition nvidia or AMD card is better for mining ether. 
https://cryptojunction.com/ethereum-mining-hardware-comparison/
Mh/s means Millions of hashes per second , the measure of mining power. 
You then work out how much power costs and how much power it uses and do some estimates on https://www.coinwarz.com/calculators/ethereum-mining-calculator

1. 
I would obtain a valid ethereum address via either a smarphone app or https://www.myetherwallet.com/
Thesee consists of 2 things - the public key (your address, forwarded anywhere you need to receive money), and the private key (needed for when you export the keysomewhere or "sweep" your account into another app someplace)
2. 
I would then proceed to mine in a mining pool, so that some consistent earnings are to be had.
eg. https://ethermine.org/
Follow the guides and you should be away.

**Comment by sahara108** [comment]
@jjisnow Thanks for your comment. I have heard that RX480 is the best GPU card for mining ether now. Low power consumption, high computational speed. It is better than other 5x series. Is that true? Do you have any idea about that?
