### ISSUE TITLE
Am I being Paranoid

### ISSUE THREAD

**Issue by paulhayes** [Genoil/cpp-ethereum#214]
Hi just trying mining ETH for the first time. Initially solo but will switch to a pool once I'm sure everything else is working ( I'm not expecting to have any success in such a short period running solo at 25MH/s ).

Ethminer is showing my target as 0. Which looks really weird. In all other posts by others the targets have been non zero
i  10:26:43|cudaminer0  set work; seed: #3868abc5, target: #000000000000

Am I doing something wrong?

**Comment by progone** [comment]
I am having the same problem with the target# 0000000000 thing

**Comment by progone** [comment]
Is anyone else experiencing this?

**Comment by paulhayes** [comment]
I'm glad it's not just me. Would be really good to know if this is normal or an issue.

**Comment by progone** [comment]
Did if you ever find out a solution for this or what is causing it?

**Comment by progone** [comment]
`modprobe: ERROR: ../libkmod/libkmod-module.c:832 kmod_module_insert_module() could not find module by name='fglrx_updates'
modprobe: ERROR: could not insert 'fglrx_updates': Unknown symbol in module, or unknown parameter (see dmesg)
Error: Fail to load fglrx kernel module!
Error! Fail to load fglrx kernel module! Maybe you can switch to root user to load kernel module directly
modprobe: ERROR: ../libkmod/libkmod-module.c:832 kmod_module_insert_module() could not find module by name='fglrx_updates'
modprobe: ERROR: could not insert 'fglrx_updates': Unknown symbol in module, or unknown parameter (see dmesg)
Error: Fail to load fglrx kernel module!
Error! Fail to load fglrx kernel module! Maybe you can switch to root user to load kernel module directly
modprobe: ERROR: ../libkmod/libkmod-module.c:832 kmod_module_insert_module() could not find module by name='fglrx_updates'
modprobe: ERROR: could not insert 'fglrx_updates': Unknown symbol in module, or unknown parameter (see dmesg)
Error: Fail to load fglrx kernel module!
Error! Fail to load fglrx kernel module! Maybe you can switch to root user to load kernel module directly
[OPENCL]:Found suitable OpenCL device [GeForce GTX 1070] with 8506769408 bytes of GPU memory`

I am wondering if this is what the issue is for`seed: #3868abc5` 'target:  #000000000000'

**Comment by progone** [comment]
I typed in console:
 `>web3.eth.defaultAccount
<undefined
>var defaultAccount = web3.eth.defaultAccount;
<undefined
>console.log(defaultAccount); // ''
✓Watch added
>web3.eth.defaultAccount = '0xc40AC1eFE57Fe0C8781B4DD9D11D269625dCe50c';
<"0xc40AC1eFE57Fe0C8781B4DD9D11D269625dCe50c"
>web3.eth.defaultAccount
<"0xc40AC1eFE57Fe0C8781B4DD9D11D269625dCe50c"
>`

I was hoping it would clear out the target:  target: #000000000000 issue.  No luck.

**Comment by paulhayes** [comment]
I switched to a mining pool, I no longer have a target of #000000000000, so I'm happy.

**Comment by progone** [comment]
Which mining pool are you using?

**Comment by paulhayes** [comment]
I went with Dwarf pool, easy setup
ethminer -U -F http://eth-eu.dwarfpool.com:80/0x[YOUR_ACCOUNT_KEY]

**Comment by progone** [comment]
I'm giving Dwarfpool a try,
First thing I noticed is this.  I'm very sleepy, I'll work on this in the morning. 
`{"id":0,"jsonrpc":"2.0","result":false,"reason":"BAD_REQ"}

`
