### ISSUE TITLE
Doesn't work with DwarfPool's Stratum-port  - http://dwarfpool.com/eth

### ISSUE THREAD

**Issue by DaveBarrron** [Genoil/cpp-ethereum#30]
C:\mine\ethminer-0.9.41-genoil-1.0.7\CUDA 7.5>ethminer  -U --farm-recheck 200 -S
 eth-us.dwarfpool.com:8008 -O 0xc835e52bd00f91ffa0ca39cf745e03986fdbb8e2 --cuda-
grid-size 8192 --cuda-block-size 128
Genoil's ethminer 0.9.41-genoil-1.0.7
=====================================================================
Forked from github.com/ethereum/cpp-ethereum
CUDA kernel ported from Tim Hughes' OpenCL kernel
With contributions from RoBiK, tpruvot and sp_

Please consider a donation to:
ETH: 0xeb9310b185455f863f526dab3d245809f6854b4d

Using grid size 8192, block size 128

  i  00:26:08|main  Connecting to stratum server eth-us.dwarfpool.com:8008
  i  00:26:08|<unknown>  Connected to stratum server eth-us.dwarfpool.com : 8008

  i  00:26:08|<unknown>  Starting farm
  i  00:26:08|<unknown>  Subscribed to stratum server
miner  00:26:08|main  Waiting for work package...
miner  00:26:08|main  Waiting for work package...
miner  00:26:08|main  Waiting for work package...
miner  00:26:09|main  Waiting for work package...

ethminer.exe has stopped working

**Comment by nerdralph** [comment]
dwarf's stratum implementation is a hack compared to coinotron's.   As far as I can tell it doesn't support vardiff.
Short of someone who really wants it submitting a patch, I'd vote against taking time to work on this.

**Comment by nerdralph** [comment]
p.s. coinmine.pl and miningpoolhub.com work fine.

**Comment by davembg** [comment]
I think it would be a good idea to support dwarf pool

**Comment by Genoil** [comment]
Apparently dwarf now also supports a clean stratum implementation. I haven't bothered to try it yet but somebody has been using my 1.0.7 with dwarf succesfilm for longer periods.

**Comment by nerdralph** [comment]
@Genoil I suspect they are just using dwarf's eth-proxy.  When I try a direct stratum connection ethminer 1.0.7 crashes (1.0.6 did too).
  i  13:39:25|<unknown>  Connected to stratum server eth-us.dwarfpool.com : 8008
  i  13:39:25|<unknown>  Starting farm
  i  13:39:25|<unknown>  Subscribed to stratum server
miner  13:39:44|main  Waiting for work package...

**Comment by Genoil** [comment]
hmm ok. anyway still not planning to support it unless someone pays me to do it ;)

**Comment by ross-p** [comment]
I understand this is a "won't fix", but in case more info is ever wanted in the future, this seems to be a non-standard response coming from dwarfpool's Stratum sever:

## Example of standard communication (ethermine, nanopool, others)

Client request:

    {"id": 2, "method": "mining.authorize", "params": ["wallet.worker","wallet.worker"]}

Server response:

    {"id":2,"jsonrpc":"2.0","result":true}

## Example of dwarfpool communication

Client request:

    {"id": 2, "method": "mining.authorize", "params": ["wallet.worker","wallet.worker"]}

Server response:

    {"result":["0xce2bd7f5f0925dd05df061e214e0e11e72509c4fafe44a582c62c4c6d2bfcba9","0xa998a7268cab7876f04cd155486b95fb33ef2ffde2d8ea3f99cdd2397d327cfb","0x0000000225c17d04dad2965cc5a02a23e254c0c3f75d9178046aeb27ce1ca574"],"jsonrpc":"2.0","id":2}

It's at this point that ethminer crashes.  It apparently expects a literal `true` result from `mining.authorize`, but instead it gets an array, and it crashes.

@Genoil you might save yourself some support questions if you throw a custom exception in this case saying something like "If you want to use dwarfpool, you must use eth-proxy because their stratum protocol is non-standard and does not work with Genoil ethminer."

**Comment by Genoil** [comment]
Use version 1.1.7 (110 branch) for Dwarfum support.

**Comment by ross-p** [comment]
Ah, I see.  The `-SP 1` argument in 1.1.7 makes it work.

Thank you!  :)
