### ISSUE TITLE
Per GPU hashrate display

### ISSUE THREAD

**Issue by Genoil** [Genoil/cpp-ethereum#83]
Is this something you can look at @nerdralph?

**Comment by nerdralph** [comment]
This would be helpful to have.  I've used the --opencl-devices option for testing individual GPUs, but per-GPU hashrate display would be better.  I've only just got comfortable with the stratum code, so it might take me a while to figure out how the hashrate calculation works.  Will give it a shot though.

**Comment by nerdralph** [comment]
Didn't turn out to be that hard to do; just pushed the changes.
ethminer  28626 15099 15099 20761 15099 21076 = 115762Khs [A54+0:R0+0:F0]
I went with Khs instead of Mhs because:
1) It displays one more significant digit in the same number of characters as Mhs to 2 decimal places.
2) The work times were counted in ms, so the math is simpler (hashcount/ms = Khs)

**Comment by Genoil** [comment]
Great! I still prefer MH/s though, because that's what most people use. Imo the extra digit is less significant than the amount of questions you have to answer to people than can't divide by 1000 ;-)

**Comment by Genoil** [comment]
still went with MH/s, but thanks for the work!
