### ISSUE TITLE
Don't crash when 1 GPU (out of N) dies

### ISSUE THREAD

**Issue by Genoil** [Genoil/cpp-ethereum#84]
Again, @nerdralph?

**Comment by nerdralph** [comment]
Wouldn't be a big priority for me.  GPUs generally hang because:
1) Overclocking too much
2) flaky risers

The solution is to look at the output to see what GPUs are still submitting shares, then fix the problematic GPU (reduce clock rate or swap riser).  When it happens with a GPU that is running stock clocks and is plugged directly into the mobo, you probably need to replace the card.

**Comment by chuckrussell1958** [comment]
Identifying the failed GPU would be helpful.
